In [1]:
import numpy as np

## element wise operation

In [2]:
a=np.array([[1,2,3],[3,3,3]])
b=np.array([[4,5,6],[2,2,2]])

In [3]:
a

array([[1, 2, 3],
       [3, 3, 3]])

In [4]:
b

array([[4, 5, 6],
       [2, 2, 2]])

In [6]:
print(a+b)

[[5 7 9]
 [5 5 5]]


In [7]:
print(a-b)

[[-3 -3 -3]
 [ 1  1  1]]


In [8]:
print(a/b)

[[0.25 0.4  0.5 ]
 [1.5  1.5  1.5 ]]


In [9]:
print(a*b)

[[ 4 10 18]
 [ 6  6  6]]


In [11]:
np.add(a,b)

array([[5, 7, 9],
       [5, 5, 5]])

In [12]:
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081],
       [1.73205081, 1.73205081, 1.73205081]])

In [14]:
np.power(a,3)

array([[ 1,  8, 27],
       [27, 27, 27]], dtype=int32)

In [15]:
np.sign(a)

array([[1, 1, 1],
       [1, 1, 1]])

In [16]:
np.sin(a)

array([[0.84147098, 0.90929743, 0.14112001],
       [0.14112001, 0.14112001, 0.14112001]])

## matrix operation

In [31]:
c=np.array([[1,2,3],[4,5,6]])
d=np.array([[2,3],[6,6]])

In [32]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
d

array([[2, 3],
       [6, 6]])

In [34]:
np.dot(c, d)

ValueError: shapes (2,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)

In [35]:
np.dot(d,c)

array([[14, 19, 24],
       [30, 42, 54]])

In [36]:
np.transpose(c)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [38]:
np.trace(c) 
# sum of diagonal element

6

In [40]:
np.linalg.det(d)


-6.0

In [42]:
np.linalg.inv(d)

array([[-1.        ,  0.5       ],
       [ 1.        , -0.33333333]])

In [44]:
np.linalg.eig(d)

(array([-0.69041576,  8.69041576]),
 array([[-0.74447562, -0.40915222],
        [ 0.66764965, -0.91246614]]))

In [52]:
a=[[1,2],[3,5]]
b=[1,2]

In [53]:
np.linalg.solve(a,b)

array([-1.,  1.])

## broadcasting

In [59]:
a=np.array([[1,2],[2,3],[4,5]])
b=np.array([10,20])

In [60]:
a


array([[1, 2],
       [2, 3],
       [4, 5]])

In [61]:
b

array([10, 20])

In [62]:
a+b

array([[11, 22],
       [12, 23],
       [14, 25]])

In [63]:
b+a

array([[11, 22],
       [12, 23],
       [14, 25]])

## why numpy over python

In [71]:
import time
a=np.random.rand(100000)
b=np.random.rand(100000)

start=time.time()
c=a*b
end=time.time()
numpy_execution_time=end-start
print("time execution by numpy{:6f}seconds".format(numpy_execution_time))

a=list(a)
b=list(b)
c=[]
start=time.time()
for i in range(len(a)):
    c.append(a[i]*b[i])
    
end=time.time()
for_loop_execution=end-start
print("time taken by loop {:6f}seconds".format(for_loop_execution))

time execution by numpy0.001996seconds
time taken by loop 0.026955seconds


In [72]:
a=np.array([[1,2],[3,4],[5,6]])
mask=np.array([True,False,True])
c=a[mask]
print(c)
            

[[1 2]
 [5 6]]


In [74]:
mask=np.array([[True,False],[True,False],[True,True]])

In [75]:
a[mask]


array([1, 3, 5, 6])

In [76]:
mask=np.array([[True,False],[True],[True,True]])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

In [77]:
a=np.array([[1,2],[3,4],[5,6]])
mask=(a>2)

In [78]:
a[mask]

array([3, 4, 5, 6])

In [79]:
a[a>2]

array([3, 4, 5, 6])

In [81]:
a[a<2]

array([1])