In [1]:
import numpy as np

In [4]:
#creat numpy array
a=np.array([1,2,3,4],dtype=np.int32)
b=np.array([1.0,2.0,3],dtype=np.float16)
c=np.array([True,False,True],dtype=np.bool_)
print(a.dtype)
print(b.dtype)
print(c.dtype)

int32
float16
bool


In [5]:
d=np.array([1,2,3],dtype=np.float64)
print(d)

[1. 2. 3.]


In [6]:
e=np.array([1.0,2.,3.],dtype=np.int64)
print(e)

[1 2 3]


In [7]:
f=np.array([True,False],dtype=np.int32)
print(f)

[1 0]


In [8]:
a.dtype

dtype('int32')

In [11]:
g=a.astype(np.float32)

In [12]:
g

array([1., 2., 3., 4.], dtype=float32)

In [15]:
a.astype(np.bool_)

array([ True,  True,  True,  True])