In [1]:
list1=[1,2,3,4,5]

In [2]:
list1[1:3]

[2, 3]

In [3]:
list1[1:3]

[2, 3]

## one dimension

In [4]:
import numpy as np

In [6]:
array1=np.array(list1)

In [7]:
array1[1:3]

array([2, 3])

## multi dimension array

In [10]:
list2=[[1,2,3,4,5],[6,7,8,9,10]]

In [11]:
list2[0][1:3]

[2, 3]

In [9]:
array2=np.array(list2)

In [12]:
array2[1][1:3]

array([7, 8])

In [13]:
array2[1,1:3]

array([7, 8])

In [16]:
array2[:,1:3]

array([[2, 3],
       [7, 8]])

In [17]:
array2[1:5:2]

array([[ 6,  7,  8,  9, 10]])

In [26]:
array2[:,1:5:2]

array([[2, 4],
       [7, 9]])

In [29]:
list3=[[1,2,3,4,5,6],[11,22,33,44,55,66],[10,20,30,40,50,60]]

In [31]:
array3=np.array(list3)

In [32]:
array3

array([[ 1,  2,  3,  4,  5,  6],
       [11, 22, 33, 44, 55, 66],
       [10, 20, 30, 40, 50, 60]])

In [34]:
array3[1:,2:5]

array([[33, 44, 55],
       [30, 40, 50]])

In [36]:
array3[:,-1:]

array([[ 6],
       [66],
       [60]])

In [37]:
array3.shape

(3, 6)

In [38]:
array3.shape[0]

3

In [44]:
list4=[[[1,2,3,4],[11,22,33,44]],[[1,2,3,4],[11,22,33,44]],[1,2,3,4],[11,22,33,44]]

In [45]:
list4

[[[1, 2, 3, 4], [11, 22, 33, 44]],
 [[1, 2, 3, 4], [11, 22, 33, 44]],
 [1, 2, 3, 4],
 [11, 22, 33, 44]]

In [46]:
array4=np.array(list4)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (4,) + inhomogeneous part.