In [1]:
import numpy as np

In [2]:
a=np.array([[1,2,3],[4,5,6]])

In [3]:
a.shape

(2, 3)

In [4]:
a.dtype

dtype('int32')

In [5]:
a.ndim

2

In [9]:
a.flatten() #matrix into list or 
#multi dimension into single dimension

array([1, 2, 3, 4, 5, 6])

In [10]:
#give sum of element
a.sum()

21

In [11]:
a.max()

6

In [12]:
a.max(axis=1)

array([3, 6])

In [14]:
a.argmax(axis=1)

array([2, 2], dtype=int64)

In [17]:
a.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [19]:
m=np.array([[1,2],[3,4]])
n=np.array([[5,6],[7,8]])

In [30]:
np.concatenate((m,n),axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [20]:
np.concatenate((m,n),axis=None)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [22]:
a=a.reshape(6)

In [23]:
np.split(a,3)

[array([1, 2]), array([3, 4]), array([5, 6])]

In [31]:
np.split(a,4)

ValueError: array split does not result in an equal division

In [33]:
np.split(a,[2,5,7])

[array([1, 2]), array([3, 4, 5]), array([6]), array([], dtype=int32)]