In [2]:
import numpy as np

## crating numpy array with np.array()

In [5]:
#creating numpy arrays
list1=[1,2,3,4]
print(type(list1))
array1=np.array(list1)
print(array1)
print(type(array1))


<class 'list'>
[1 2 3 4]
<class 'numpy.ndarray'>


In [9]:
list2=[[1,2],[3,4]]
print(type(list2))

<class 'list'>


In [7]:
array2=np.array(list2)

In [10]:
print(array2)
print(type(array2))

[[1 2]
 [3 4]]
<class 'numpy.ndarray'>


## np.zeros

In [11]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

## np.ones

In [22]:
print(np.ones(5))

[1. 1. 1. 1. 1.]


In [26]:
print(np.ones((3,4,3)))

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


## np.full()

In [29]:
print(np.full(5,2))

[2 2 2 2 2]


In [30]:
print(np.full(2,3))

[3 3]


In [33]:
print(np.full((2,3),-2))

[[-2 -2 -2]
 [-2 -2 -2]]


## np.arange()

In [41]:
print(np.arange(2,8,2))

[2 4 6]


In [42]:
print(np.arange(5))

[0 1 2 3 4]


In [43]:
print(np.arange(2,10))

[2 3 4 5 6 7 8 9]


## np.linspace()

In [44]:
#np.linspace(start,stop,num of element in between)

np.linspace(-2,3,num=5)

array([-2.  , -0.75,  0.5 ,  1.75,  3.  ])

In [47]:
print(np.linspace(1,10,4))

[ 1.  4.  7. 10.]


In [51]:
np.linspace((1,2),(5,10),5)

array([[ 1.,  2.],
       [ 2.,  4.],
       [ 3.,  6.],
       [ 4.,  8.],
       [ 5., 10.]])

In [52]:
np.linspace((1,2,3),(5,10,15),3)

array([[ 1.,  2.,  3.],
       [ 3.,  6.,  9.],
       [ 5., 10., 15.]])

## np.diag()

In [53]:
np.diag([2,3,4])

array([[2, 0, 0],
       [0, 3, 0],
       [0, 0, 4]])

In [54]:
np.diag([2,3,4],k=2)

array([[0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [55]:
np.diag([2,3,4],k=-1)

array([[0, 0, 0, 0],
       [2, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 4, 0]])

In [56]:
np.diag([2,3,4],k=-2)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [2, 0, 0, 0, 0],
       [0, 3, 0, 0, 0],
       [0, 0, 4, 0, 0]])

## np.eye()

In [58]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [59]:
np.eye(5,k=-1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [60]:
np.eye(5,k=1)

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

## np.identity()

In [61]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## np.random.rand

In [64]:
np.random.rand(2,3)

array([[0.35488301, 0.65852971, 0.63776452],
       [0.48252866, 0.48299016, 0.64490877]])

In [68]:
np.random.rand(4)

array([0.49969287, 0.80696721, 0.16421473, 0.00764067])

In [81]:
np.random.randint(80,size=(3,2))

array([[52, 50],
       [55,  2],
       [71,  1]])

In [82]:
np.random.randint(1,20,size=(2,2))

array([[ 4,  6],
       [12, 19]])

## indexing and slicing

In [83]:
list1=[1,2,3,4]


## single dimension

In [84]:
list1[2]

3

In [85]:
np1=np.array(list1)

In [86]:
np1[1]

2

## multi dimension

In [91]:
list2=[[11,22,33,44],[1,2,3,4]]

In [99]:
list2[1][3]

4

In [94]:
np2=np.array(list2)
print(np2)

[[11 22 33 44]
 [ 1  2  3  4]]


In [93]:
np2[0][2]

33

In [96]:
np2[0,2]

33